// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/LukeHagar/plexgo/models/components"
	"net/http"
)

// CreateDownloadQueueMediaContainer - `MediaContainer` is the root element of most Plex API responses. It serves as a generic container for various types of content (Metadata, Hubs, Directories, etc.) and includes pagination information (offset, size, totalSize) when applicable.
// Common attributes: - identifier: Unique identifier for this container - size: Number of items in this response page - totalSize: Total number of items available (for pagination) - offset: Starting index of this page (for pagination)
// The container often "hoists" common attributes from its children. For example, if all tracks in a container share the same album title, the `parentTitle` attribute may appear on the MediaContainer rather than being repeated on each track.
type CreateDownloadQueueMediaContainer struct {
	Identifier *string `json:"identifier,omitempty"`
	// The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
	Offset *int64 `json:"offset,omitempty"`
	Size   *int64 `json:"size,omitempty"`
	// The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
	TotalSize     *int64                     `json:"totalSize,omitempty"`
	DownloadQueue []components.DownloadQueue `json:"DownloadQueue,omitempty"`
}

func (c *CreateDownloadQueueMediaContainer) GetIdentifier() *string {
	if c == nil {
		return nil
	}
	return c.Identifier
}

func (c *CreateDownloadQueueMediaContainer) GetOffset() *int64 {
	if c == nil {
		return nil
	}
	return c.Offset
}

func (c *CreateDownloadQueueMediaContainer) GetSize() *int64 {
	if c == nil {
		return nil
	}
	return c.Size
}

func (c *CreateDownloadQueueMediaContainer) GetTotalSize() *int64 {
	if c == nil {
		return nil
	}
	return c.TotalSize
}

func (c *CreateDownloadQueueMediaContainer) GetDownloadQueue() []components.DownloadQueue {
	if c == nil {
		return nil
	}
	return c.DownloadQueue
}

// CreateDownloadQueueResponseBody - OK
type CreateDownloadQueueResponseBody struct {
	MediaContainer *CreateDownloadQueueMediaContainer `json:"MediaContainer,omitempty"`
}

func (c *CreateDownloadQueueResponseBody) GetMediaContainer() *CreateDownloadQueueMediaContainer {
	if c == nil {
		return nil
	}
	return c.MediaContainer
}

type CreateDownloadQueueResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *CreateDownloadQueueResponseBody
}

func (c *CreateDownloadQueueResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateDownloadQueueResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateDownloadQueueResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateDownloadQueueResponse) GetObject() *CreateDownloadQueueResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
