// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/LukeHagar/plexgo/internal/utils"
	"github.com/LukeHagar/plexgo/models/components"
	"net/http"
)

type DeleteLineupGlobals struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
}

func (d DeleteLineupGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteLineupGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteLineupGlobals) GetAccepts() *components.Accepts {
	if d == nil {
		return nil
	}
	return d.Accepts
}

func (d *DeleteLineupGlobals) GetClientIdentifier() *string {
	if d == nil {
		return nil
	}
	return d.ClientIdentifier
}

func (d *DeleteLineupGlobals) GetProduct() *string {
	if d == nil {
		return nil
	}
	return d.Product
}

func (d *DeleteLineupGlobals) GetVersion() *string {
	if d == nil {
		return nil
	}
	return d.Version
}

func (d *DeleteLineupGlobals) GetPlatform() *string {
	if d == nil {
		return nil
	}
	return d.Platform
}

func (d *DeleteLineupGlobals) GetPlatformVersion() *string {
	if d == nil {
		return nil
	}
	return d.PlatformVersion
}

func (d *DeleteLineupGlobals) GetDevice() *string {
	if d == nil {
		return nil
	}
	return d.Device
}

func (d *DeleteLineupGlobals) GetModel() *string {
	if d == nil {
		return nil
	}
	return d.Model
}

func (d *DeleteLineupGlobals) GetDeviceVendor() *string {
	if d == nil {
		return nil
	}
	return d.DeviceVendor
}

func (d *DeleteLineupGlobals) GetDeviceName() *string {
	if d == nil {
		return nil
	}
	return d.DeviceName
}

func (d *DeleteLineupGlobals) GetMarketplace() *string {
	if d == nil {
		return nil
	}
	return d.Marketplace
}

type DeleteLineupRequest struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
	// The ID of the DVR.
	DvrID int64 `pathParam:"style=simple,explode=false,name=dvrId"`
	// The lineup to delete
	Lineup string `queryParam:"style=form,explode=true,name=lineup"`
}

func (d DeleteLineupRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteLineupRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteLineupRequest) GetAccepts() *components.Accepts {
	if d == nil {
		return nil
	}
	return d.Accepts
}

func (d *DeleteLineupRequest) GetClientIdentifier() *string {
	if d == nil {
		return nil
	}
	return d.ClientIdentifier
}

func (d *DeleteLineupRequest) GetProduct() *string {
	if d == nil {
		return nil
	}
	return d.Product
}

func (d *DeleteLineupRequest) GetVersion() *string {
	if d == nil {
		return nil
	}
	return d.Version
}

func (d *DeleteLineupRequest) GetPlatform() *string {
	if d == nil {
		return nil
	}
	return d.Platform
}

func (d *DeleteLineupRequest) GetPlatformVersion() *string {
	if d == nil {
		return nil
	}
	return d.PlatformVersion
}

func (d *DeleteLineupRequest) GetDevice() *string {
	if d == nil {
		return nil
	}
	return d.Device
}

func (d *DeleteLineupRequest) GetModel() *string {
	if d == nil {
		return nil
	}
	return d.Model
}

func (d *DeleteLineupRequest) GetDeviceVendor() *string {
	if d == nil {
		return nil
	}
	return d.DeviceVendor
}

func (d *DeleteLineupRequest) GetDeviceName() *string {
	if d == nil {
		return nil
	}
	return d.DeviceName
}

func (d *DeleteLineupRequest) GetMarketplace() *string {
	if d == nil {
		return nil
	}
	return d.Marketplace
}

func (d *DeleteLineupRequest) GetDvrID() int64 {
	if d == nil {
		return 0
	}
	return d.DvrID
}

func (d *DeleteLineupRequest) GetLineup() string {
	if d == nil {
		return ""
	}
	return d.Lineup
}

type DeleteLineupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DVRResponse *components.DVRResponse
	Headers     map[string][]string
}

func (d *DeleteLineupResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteLineupResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteLineupResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteLineupResponse) GetDVRResponse() *components.DVRResponse {
	if d == nil {
		return nil
	}
	return d.DVRResponse
}

func (d *DeleteLineupResponse) GetHeaders() map[string][]string {
	if d == nil {
		return map[string][]string{}
	}
	return d.Headers
}
