// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/LukeHagar/plexgo/internal/utils"
	"github.com/LukeHagar/plexgo/models/components"
	"io"
	"net/http"
)

type DownloadLogBundleGlobals struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
}

func (d DownloadLogBundleGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DownloadLogBundleGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DownloadLogBundleGlobals) GetAccepts() *components.Accepts {
	if d == nil {
		return nil
	}
	return d.Accepts
}

func (d *DownloadLogBundleGlobals) GetClientIdentifier() *string {
	if d == nil {
		return nil
	}
	return d.ClientIdentifier
}

func (d *DownloadLogBundleGlobals) GetProduct() *string {
	if d == nil {
		return nil
	}
	return d.Product
}

func (d *DownloadLogBundleGlobals) GetVersion() *string {
	if d == nil {
		return nil
	}
	return d.Version
}

func (d *DownloadLogBundleGlobals) GetPlatform() *string {
	if d == nil {
		return nil
	}
	return d.Platform
}

func (d *DownloadLogBundleGlobals) GetPlatformVersion() *string {
	if d == nil {
		return nil
	}
	return d.PlatformVersion
}

func (d *DownloadLogBundleGlobals) GetDevice() *string {
	if d == nil {
		return nil
	}
	return d.Device
}

func (d *DownloadLogBundleGlobals) GetModel() *string {
	if d == nil {
		return nil
	}
	return d.Model
}

func (d *DownloadLogBundleGlobals) GetDeviceVendor() *string {
	if d == nil {
		return nil
	}
	return d.DeviceVendor
}

func (d *DownloadLogBundleGlobals) GetDeviceName() *string {
	if d == nil {
		return nil
	}
	return d.DeviceName
}

func (d *DownloadLogBundleGlobals) GetMarketplace() *string {
	if d == nil {
		return nil
	}
	return d.Marketplace
}

type DownloadLogBundleRequest struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
}

func (d DownloadLogBundleRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DownloadLogBundleRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DownloadLogBundleRequest) GetAccepts() *components.Accepts {
	if d == nil {
		return nil
	}
	return d.Accepts
}

func (d *DownloadLogBundleRequest) GetClientIdentifier() *string {
	if d == nil {
		return nil
	}
	return d.ClientIdentifier
}

func (d *DownloadLogBundleRequest) GetProduct() *string {
	if d == nil {
		return nil
	}
	return d.Product
}

func (d *DownloadLogBundleRequest) GetVersion() *string {
	if d == nil {
		return nil
	}
	return d.Version
}

func (d *DownloadLogBundleRequest) GetPlatform() *string {
	if d == nil {
		return nil
	}
	return d.Platform
}

func (d *DownloadLogBundleRequest) GetPlatformVersion() *string {
	if d == nil {
		return nil
	}
	return d.PlatformVersion
}

func (d *DownloadLogBundleRequest) GetDevice() *string {
	if d == nil {
		return nil
	}
	return d.Device
}

func (d *DownloadLogBundleRequest) GetModel() *string {
	if d == nil {
		return nil
	}
	return d.Model
}

func (d *DownloadLogBundleRequest) GetDeviceVendor() *string {
	if d == nil {
		return nil
	}
	return d.DeviceVendor
}

func (d *DownloadLogBundleRequest) GetDeviceName() *string {
	if d == nil {
		return nil
	}
	return d.DeviceName
}

func (d *DownloadLogBundleRequest) GetMarketplace() *string {
	if d == nil {
		return nil
	}
	return d.Marketplace
}

type DownloadLogBundleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	BinaryResponse io.ReadCloser
}

func (d *DownloadLogBundleResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DownloadLogBundleResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DownloadLogBundleResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DownloadLogBundleResponse) GetBinaryResponse() io.ReadCloser {
	if d == nil {
		return nil
	}
	return d.BinaryResponse
}
