// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/LukeHagar/plexgo/internal/utils"
	"github.com/LukeHagar/plexgo/models/components"
	"net/http"
)

type EmptyTrashPutGlobals struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
}

func (e EmptyTrashPutGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EmptyTrashPutGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EmptyTrashPutGlobals) GetAccepts() *components.Accepts {
	if e == nil {
		return nil
	}
	return e.Accepts
}

func (e *EmptyTrashPutGlobals) GetClientIdentifier() *string {
	if e == nil {
		return nil
	}
	return e.ClientIdentifier
}

func (e *EmptyTrashPutGlobals) GetProduct() *string {
	if e == nil {
		return nil
	}
	return e.Product
}

func (e *EmptyTrashPutGlobals) GetVersion() *string {
	if e == nil {
		return nil
	}
	return e.Version
}

func (e *EmptyTrashPutGlobals) GetPlatform() *string {
	if e == nil {
		return nil
	}
	return e.Platform
}

func (e *EmptyTrashPutGlobals) GetPlatformVersion() *string {
	if e == nil {
		return nil
	}
	return e.PlatformVersion
}

func (e *EmptyTrashPutGlobals) GetDevice() *string {
	if e == nil {
		return nil
	}
	return e.Device
}

func (e *EmptyTrashPutGlobals) GetModel() *string {
	if e == nil {
		return nil
	}
	return e.Model
}

func (e *EmptyTrashPutGlobals) GetDeviceVendor() *string {
	if e == nil {
		return nil
	}
	return e.DeviceVendor
}

func (e *EmptyTrashPutGlobals) GetDeviceName() *string {
	if e == nil {
		return nil
	}
	return e.DeviceName
}

func (e *EmptyTrashPutGlobals) GetMarketplace() *string {
	if e == nil {
		return nil
	}
	return e.Marketplace
}

type EmptyTrashPutRequest struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
	// Section identifier
	SectionID int64 `pathParam:"style=simple,explode=false,name=sectionId"`
}

func (e EmptyTrashPutRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EmptyTrashPutRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EmptyTrashPutRequest) GetAccepts() *components.Accepts {
	if e == nil {
		return nil
	}
	return e.Accepts
}

func (e *EmptyTrashPutRequest) GetClientIdentifier() *string {
	if e == nil {
		return nil
	}
	return e.ClientIdentifier
}

func (e *EmptyTrashPutRequest) GetProduct() *string {
	if e == nil {
		return nil
	}
	return e.Product
}

func (e *EmptyTrashPutRequest) GetVersion() *string {
	if e == nil {
		return nil
	}
	return e.Version
}

func (e *EmptyTrashPutRequest) GetPlatform() *string {
	if e == nil {
		return nil
	}
	return e.Platform
}

func (e *EmptyTrashPutRequest) GetPlatformVersion() *string {
	if e == nil {
		return nil
	}
	return e.PlatformVersion
}

func (e *EmptyTrashPutRequest) GetDevice() *string {
	if e == nil {
		return nil
	}
	return e.Device
}

func (e *EmptyTrashPutRequest) GetModel() *string {
	if e == nil {
		return nil
	}
	return e.Model
}

func (e *EmptyTrashPutRequest) GetDeviceVendor() *string {
	if e == nil {
		return nil
	}
	return e.DeviceVendor
}

func (e *EmptyTrashPutRequest) GetDeviceName() *string {
	if e == nil {
		return nil
	}
	return e.DeviceName
}

func (e *EmptyTrashPutRequest) GetMarketplace() *string {
	if e == nil {
		return nil
	}
	return e.Marketplace
}

func (e *EmptyTrashPutRequest) GetSectionID() int64 {
	if e == nil {
		return 0
	}
	return e.SectionID
}

type EmptyTrashPutResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (e *EmptyTrashPutResponse) GetContentType() string {
	if e == nil {
		return ""
	}
	return e.ContentType
}

func (e *EmptyTrashPutResponse) GetStatusCode() int {
	if e == nil {
		return 0
	}
	return e.StatusCode
}

func (e *EmptyTrashPutResponse) GetRawResponse() *http.Response {
	if e == nil {
		return nil
	}
	return e.RawResponse
}
