// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/LukeHagar/plexgo/models/components"
	"net/http"
)

var GetFeaturesServerList = []string{
	"https://plex.tv/api/v2",
}

// GetFeaturesResponseBody - OK
type GetFeaturesResponseBody struct {
	Type      *string                `json:"type,omitempty"`
	Directory []components.Directory `json:"Directory,omitempty"`
	Key       *string                `json:"key,omitempty"`
}

func (g *GetFeaturesResponseBody) GetType() *string {
	if g == nil {
		return nil
	}
	return g.Type
}

func (g *GetFeaturesResponseBody) GetDirectory() []components.Directory {
	if g == nil {
		return nil
	}
	return g.Directory
}

func (g *GetFeaturesResponseBody) GetKey() *string {
	if g == nil {
		return nil
	}
	return g.Key
}

type GetFeaturesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *GetFeaturesResponseBody
}

func (g *GetFeaturesResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetFeaturesResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetFeaturesResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetFeaturesResponse) GetObject() *GetFeaturesResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
