// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/LukeHagar/plexgo/models/components"
	"net/http"
)

var LinkOAuthPinServerList = []string{
	"https://plex.tv/api/v2",
}

type LinkOAuthPinAuthenticationRequestBody struct {
	AuthToken *string `json:"authToken,omitempty"`
	Pin       *string `json:"pin,omitempty"`
}

func (l *LinkOAuthPinAuthenticationRequestBody) GetAuthToken() *string {
	if l == nil {
		return nil
	}
	return l.AuthToken
}

func (l *LinkOAuthPinAuthenticationRequestBody) GetPin() *string {
	if l == nil {
		return nil
	}
	return l.Pin
}

type LinkOAuthPinResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	SuccessResponse *components.SuccessResponse
}

func (l *LinkOAuthPinResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *LinkOAuthPinResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *LinkOAuthPinResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *LinkOAuthPinResponse) GetSuccessResponse() *components.SuccessResponse {
	if l == nil {
		return nil
	}
	return l.SuccessResponse
}
