// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/LukeHagar/plexgo/internal/utils"
	"github.com/LukeHagar/plexgo/models/components"
	"net/http"
)

type OptimizeSectionPostGlobals struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
}

func (o OptimizeSectionPostGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OptimizeSectionPostGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OptimizeSectionPostGlobals) GetAccepts() *components.Accepts {
	if o == nil {
		return nil
	}
	return o.Accepts
}

func (o *OptimizeSectionPostGlobals) GetClientIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.ClientIdentifier
}

func (o *OptimizeSectionPostGlobals) GetProduct() *string {
	if o == nil {
		return nil
	}
	return o.Product
}

func (o *OptimizeSectionPostGlobals) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *OptimizeSectionPostGlobals) GetPlatform() *string {
	if o == nil {
		return nil
	}
	return o.Platform
}

func (o *OptimizeSectionPostGlobals) GetPlatformVersion() *string {
	if o == nil {
		return nil
	}
	return o.PlatformVersion
}

func (o *OptimizeSectionPostGlobals) GetDevice() *string {
	if o == nil {
		return nil
	}
	return o.Device
}

func (o *OptimizeSectionPostGlobals) GetModel() *string {
	if o == nil {
		return nil
	}
	return o.Model
}

func (o *OptimizeSectionPostGlobals) GetDeviceVendor() *string {
	if o == nil {
		return nil
	}
	return o.DeviceVendor
}

func (o *OptimizeSectionPostGlobals) GetDeviceName() *string {
	if o == nil {
		return nil
	}
	return o.DeviceName
}

func (o *OptimizeSectionPostGlobals) GetMarketplace() *string {
	if o == nil {
		return nil
	}
	return o.Marketplace
}

type OptimizeSectionPostRequest struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
	// The unique identifier of the library section
	SectionID int64 `pathParam:"style=simple,explode=false,name=sectionId"`
}

func (o OptimizeSectionPostRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OptimizeSectionPostRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OptimizeSectionPostRequest) GetAccepts() *components.Accepts {
	if o == nil {
		return nil
	}
	return o.Accepts
}

func (o *OptimizeSectionPostRequest) GetClientIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.ClientIdentifier
}

func (o *OptimizeSectionPostRequest) GetProduct() *string {
	if o == nil {
		return nil
	}
	return o.Product
}

func (o *OptimizeSectionPostRequest) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *OptimizeSectionPostRequest) GetPlatform() *string {
	if o == nil {
		return nil
	}
	return o.Platform
}

func (o *OptimizeSectionPostRequest) GetPlatformVersion() *string {
	if o == nil {
		return nil
	}
	return o.PlatformVersion
}

func (o *OptimizeSectionPostRequest) GetDevice() *string {
	if o == nil {
		return nil
	}
	return o.Device
}

func (o *OptimizeSectionPostRequest) GetModel() *string {
	if o == nil {
		return nil
	}
	return o.Model
}

func (o *OptimizeSectionPostRequest) GetDeviceVendor() *string {
	if o == nil {
		return nil
	}
	return o.DeviceVendor
}

func (o *OptimizeSectionPostRequest) GetDeviceName() *string {
	if o == nil {
		return nil
	}
	return o.DeviceName
}

func (o *OptimizeSectionPostRequest) GetMarketplace() *string {
	if o == nil {
		return nil
	}
	return o.Marketplace
}

func (o *OptimizeSectionPostRequest) GetSectionID() int64 {
	if o == nil {
		return 0
	}
	return o.SectionID
}

type OptimizeSectionPostResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	SuccessResponse *components.SuccessResponse
}

func (o *OptimizeSectionPostResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *OptimizeSectionPostResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *OptimizeSectionPostResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *OptimizeSectionPostResponse) GetSuccessResponse() *components.SuccessResponse {
	if o == nil {
		return nil
	}
	return o.SuccessResponse
}
