// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/LukeHagar/plexgo/internal/utils"
	"github.com/LukeHagar/plexgo/models/components"
	"net/http"
)

type PatchDVRSettingsGlobals struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
}

func (p PatchDVRSettingsGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatchDVRSettingsGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatchDVRSettingsGlobals) GetAccepts() *components.Accepts {
	if p == nil {
		return nil
	}
	return p.Accepts
}

func (p *PatchDVRSettingsGlobals) GetClientIdentifier() *string {
	if p == nil {
		return nil
	}
	return p.ClientIdentifier
}

func (p *PatchDVRSettingsGlobals) GetProduct() *string {
	if p == nil {
		return nil
	}
	return p.Product
}

func (p *PatchDVRSettingsGlobals) GetVersion() *string {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *PatchDVRSettingsGlobals) GetPlatform() *string {
	if p == nil {
		return nil
	}
	return p.Platform
}

func (p *PatchDVRSettingsGlobals) GetPlatformVersion() *string {
	if p == nil {
		return nil
	}
	return p.PlatformVersion
}

func (p *PatchDVRSettingsGlobals) GetDevice() *string {
	if p == nil {
		return nil
	}
	return p.Device
}

func (p *PatchDVRSettingsGlobals) GetModel() *string {
	if p == nil {
		return nil
	}
	return p.Model
}

func (p *PatchDVRSettingsGlobals) GetDeviceVendor() *string {
	if p == nil {
		return nil
	}
	return p.DeviceVendor
}

func (p *PatchDVRSettingsGlobals) GetDeviceName() *string {
	if p == nil {
		return nil
	}
	return p.DeviceName
}

func (p *PatchDVRSettingsGlobals) GetMarketplace() *string {
	if p == nil {
		return nil
	}
	return p.Marketplace
}

type PatchDVRSettingsRequest struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
	// The ID of the DVR.
	DvrID int64 `pathParam:"style=simple,explode=false,name=dvrId"`
}

func (p PatchDVRSettingsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatchDVRSettingsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatchDVRSettingsRequest) GetAccepts() *components.Accepts {
	if p == nil {
		return nil
	}
	return p.Accepts
}

func (p *PatchDVRSettingsRequest) GetClientIdentifier() *string {
	if p == nil {
		return nil
	}
	return p.ClientIdentifier
}

func (p *PatchDVRSettingsRequest) GetProduct() *string {
	if p == nil {
		return nil
	}
	return p.Product
}

func (p *PatchDVRSettingsRequest) GetVersion() *string {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *PatchDVRSettingsRequest) GetPlatform() *string {
	if p == nil {
		return nil
	}
	return p.Platform
}

func (p *PatchDVRSettingsRequest) GetPlatformVersion() *string {
	if p == nil {
		return nil
	}
	return p.PlatformVersion
}

func (p *PatchDVRSettingsRequest) GetDevice() *string {
	if p == nil {
		return nil
	}
	return p.Device
}

func (p *PatchDVRSettingsRequest) GetModel() *string {
	if p == nil {
		return nil
	}
	return p.Model
}

func (p *PatchDVRSettingsRequest) GetDeviceVendor() *string {
	if p == nil {
		return nil
	}
	return p.DeviceVendor
}

func (p *PatchDVRSettingsRequest) GetDeviceName() *string {
	if p == nil {
		return nil
	}
	return p.DeviceName
}

func (p *PatchDVRSettingsRequest) GetMarketplace() *string {
	if p == nil {
		return nil
	}
	return p.Marketplace
}

func (p *PatchDVRSettingsRequest) GetDvrID() int64 {
	if p == nil {
		return 0
	}
	return p.DvrID
}

type PatchDVRSettingsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	SuccessResponse *components.SuccessResponse
}

func (p *PatchDVRSettingsResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchDVRSettingsResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchDVRSettingsResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PatchDVRSettingsResponse) GetSuccessResponse() *components.SuccessResponse {
	if p == nil {
		return nil
	}
	return p.SuccessResponse
}
