// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/LukeHagar/plexgo/models/components"
	"net/http"
)

var PingServerList = []string{
	"https://plex.tv/api/v2",
}

type PingResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	SuccessResponse *components.SuccessResponse
}

func (p *PingResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PingResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PingResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PingResponse) GetSuccessResponse() *components.SuccessResponse {
	if p == nil {
		return nil
	}
	return p.SuccessResponse
}
