// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/LukeHagar/plexgo/internal/utils"
	"github.com/LukeHagar/plexgo/models/components"
	"net/http"
)

type PlayerSetViewOffsetGlobals struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
}

func (p PlayerSetViewOffsetGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlayerSetViewOffsetGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlayerSetViewOffsetGlobals) GetAccepts() *components.Accepts {
	if p == nil {
		return nil
	}
	return p.Accepts
}

func (p *PlayerSetViewOffsetGlobals) GetClientIdentifier() *string {
	if p == nil {
		return nil
	}
	return p.ClientIdentifier
}

func (p *PlayerSetViewOffsetGlobals) GetProduct() *string {
	if p == nil {
		return nil
	}
	return p.Product
}

func (p *PlayerSetViewOffsetGlobals) GetVersion() *string {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *PlayerSetViewOffsetGlobals) GetPlatform() *string {
	if p == nil {
		return nil
	}
	return p.Platform
}

func (p *PlayerSetViewOffsetGlobals) GetPlatformVersion() *string {
	if p == nil {
		return nil
	}
	return p.PlatformVersion
}

func (p *PlayerSetViewOffsetGlobals) GetDevice() *string {
	if p == nil {
		return nil
	}
	return p.Device
}

func (p *PlayerSetViewOffsetGlobals) GetModel() *string {
	if p == nil {
		return nil
	}
	return p.Model
}

func (p *PlayerSetViewOffsetGlobals) GetDeviceVendor() *string {
	if p == nil {
		return nil
	}
	return p.DeviceVendor
}

func (p *PlayerSetViewOffsetGlobals) GetDeviceName() *string {
	if p == nil {
		return nil
	}
	return p.DeviceName
}

func (p *PlayerSetViewOffsetGlobals) GetMarketplace() *string {
	if p == nil {
		return nil
	}
	return p.Marketplace
}

type PlayerSetViewOffsetRequest struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
	// The client identifier of the target device to control. If omitted, the command is sent to the default/active client.
	XPlexTargetClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Target-Client-Identifier"`
	// The byte offset for stream seeking
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (p PlayerSetViewOffsetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlayerSetViewOffsetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlayerSetViewOffsetRequest) GetAccepts() *components.Accepts {
	if p == nil {
		return nil
	}
	return p.Accepts
}

func (p *PlayerSetViewOffsetRequest) GetClientIdentifier() *string {
	if p == nil {
		return nil
	}
	return p.ClientIdentifier
}

func (p *PlayerSetViewOffsetRequest) GetProduct() *string {
	if p == nil {
		return nil
	}
	return p.Product
}

func (p *PlayerSetViewOffsetRequest) GetVersion() *string {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *PlayerSetViewOffsetRequest) GetPlatform() *string {
	if p == nil {
		return nil
	}
	return p.Platform
}

func (p *PlayerSetViewOffsetRequest) GetPlatformVersion() *string {
	if p == nil {
		return nil
	}
	return p.PlatformVersion
}

func (p *PlayerSetViewOffsetRequest) GetDevice() *string {
	if p == nil {
		return nil
	}
	return p.Device
}

func (p *PlayerSetViewOffsetRequest) GetModel() *string {
	if p == nil {
		return nil
	}
	return p.Model
}

func (p *PlayerSetViewOffsetRequest) GetDeviceVendor() *string {
	if p == nil {
		return nil
	}
	return p.DeviceVendor
}

func (p *PlayerSetViewOffsetRequest) GetDeviceName() *string {
	if p == nil {
		return nil
	}
	return p.DeviceName
}

func (p *PlayerSetViewOffsetRequest) GetMarketplace() *string {
	if p == nil {
		return nil
	}
	return p.Marketplace
}

func (p *PlayerSetViewOffsetRequest) GetXPlexTargetClientIdentifier() *string {
	if p == nil {
		return nil
	}
	return p.XPlexTargetClientIdentifier
}

func (p *PlayerSetViewOffsetRequest) GetOffset() *int64 {
	if p == nil {
		return nil
	}
	return p.Offset
}

type PlayerSetViewOffsetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	SuccessResponse *components.SuccessResponse
}

func (p *PlayerSetViewOffsetResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PlayerSetViewOffsetResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PlayerSetViewOffsetResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PlayerSetViewOffsetResponse) GetSuccessResponse() *components.SuccessResponse {
	if p == nil {
		return nil
	}
	return p.SuccessResponse
}
