// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/LukeHagar/plexgo/internal/utils"
	"github.com/LukeHagar/plexgo/models/components"
	"io"
	"net/http"
)

type PlayerSetTextStreamGlobals struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
}

func (p PlayerSetTextStreamGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlayerSetTextStreamGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlayerSetTextStreamGlobals) GetAccepts() *components.Accepts {
	if p == nil {
		return nil
	}
	return p.Accepts
}

func (p *PlayerSetTextStreamGlobals) GetClientIdentifier() *string {
	if p == nil {
		return nil
	}
	return p.ClientIdentifier
}

func (p *PlayerSetTextStreamGlobals) GetProduct() *string {
	if p == nil {
		return nil
	}
	return p.Product
}

func (p *PlayerSetTextStreamGlobals) GetVersion() *string {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *PlayerSetTextStreamGlobals) GetPlatform() *string {
	if p == nil {
		return nil
	}
	return p.Platform
}

func (p *PlayerSetTextStreamGlobals) GetPlatformVersion() *string {
	if p == nil {
		return nil
	}
	return p.PlatformVersion
}

func (p *PlayerSetTextStreamGlobals) GetDevice() *string {
	if p == nil {
		return nil
	}
	return p.Device
}

func (p *PlayerSetTextStreamGlobals) GetModel() *string {
	if p == nil {
		return nil
	}
	return p.Model
}

func (p *PlayerSetTextStreamGlobals) GetDeviceVendor() *string {
	if p == nil {
		return nil
	}
	return p.DeviceVendor
}

func (p *PlayerSetTextStreamGlobals) GetDeviceName() *string {
	if p == nil {
		return nil
	}
	return p.DeviceName
}

func (p *PlayerSetTextStreamGlobals) GetMarketplace() *string {
	if p == nil {
		return nil
	}
	return p.Marketplace
}

type PlayerSetTextStreamRequest struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
	// The client identifier of the target device to control. If omitted, the command is sent to the default/active client.
	XPlexTargetClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Target-Client-Identifier"`
	// The unique identifier of the stream
	StreamID *int64 `queryParam:"style=form,explode=true,name=streamID"`
}

func (p PlayerSetTextStreamRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlayerSetTextStreamRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlayerSetTextStreamRequest) GetAccepts() *components.Accepts {
	if p == nil {
		return nil
	}
	return p.Accepts
}

func (p *PlayerSetTextStreamRequest) GetClientIdentifier() *string {
	if p == nil {
		return nil
	}
	return p.ClientIdentifier
}

func (p *PlayerSetTextStreamRequest) GetProduct() *string {
	if p == nil {
		return nil
	}
	return p.Product
}

func (p *PlayerSetTextStreamRequest) GetVersion() *string {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *PlayerSetTextStreamRequest) GetPlatform() *string {
	if p == nil {
		return nil
	}
	return p.Platform
}

func (p *PlayerSetTextStreamRequest) GetPlatformVersion() *string {
	if p == nil {
		return nil
	}
	return p.PlatformVersion
}

func (p *PlayerSetTextStreamRequest) GetDevice() *string {
	if p == nil {
		return nil
	}
	return p.Device
}

func (p *PlayerSetTextStreamRequest) GetModel() *string {
	if p == nil {
		return nil
	}
	return p.Model
}

func (p *PlayerSetTextStreamRequest) GetDeviceVendor() *string {
	if p == nil {
		return nil
	}
	return p.DeviceVendor
}

func (p *PlayerSetTextStreamRequest) GetDeviceName() *string {
	if p == nil {
		return nil
	}
	return p.DeviceName
}

func (p *PlayerSetTextStreamRequest) GetMarketplace() *string {
	if p == nil {
		return nil
	}
	return p.Marketplace
}

func (p *PlayerSetTextStreamRequest) GetXPlexTargetClientIdentifier() *string {
	if p == nil {
		return nil
	}
	return p.XPlexTargetClientIdentifier
}

func (p *PlayerSetTextStreamRequest) GetStreamID() *int64 {
	if p == nil {
		return nil
	}
	return p.StreamID
}

type PlayerSetTextStreamResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	BinaryResponse io.ReadCloser
}

func (p *PlayerSetTextStreamResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PlayerSetTextStreamResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PlayerSetTextStreamResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PlayerSetTextStreamResponse) GetBinaryResponse() io.ReadCloser {
	if p == nil {
		return nil
	}
	return p.BinaryResponse
}
