// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/LukeHagar/plexgo/internal/utils"
	"github.com/LukeHagar/plexgo/models/components"
	"net/http"
)

type PlayerSetStateGlobals struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
}

func (p PlayerSetStateGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlayerSetStateGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlayerSetStateGlobals) GetAccepts() *components.Accepts {
	if p == nil {
		return nil
	}
	return p.Accepts
}

func (p *PlayerSetStateGlobals) GetClientIdentifier() *string {
	if p == nil {
		return nil
	}
	return p.ClientIdentifier
}

func (p *PlayerSetStateGlobals) GetProduct() *string {
	if p == nil {
		return nil
	}
	return p.Product
}

func (p *PlayerSetStateGlobals) GetVersion() *string {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *PlayerSetStateGlobals) GetPlatform() *string {
	if p == nil {
		return nil
	}
	return p.Platform
}

func (p *PlayerSetStateGlobals) GetPlatformVersion() *string {
	if p == nil {
		return nil
	}
	return p.PlatformVersion
}

func (p *PlayerSetStateGlobals) GetDevice() *string {
	if p == nil {
		return nil
	}
	return p.Device
}

func (p *PlayerSetStateGlobals) GetModel() *string {
	if p == nil {
		return nil
	}
	return p.Model
}

func (p *PlayerSetStateGlobals) GetDeviceVendor() *string {
	if p == nil {
		return nil
	}
	return p.DeviceVendor
}

func (p *PlayerSetStateGlobals) GetDeviceName() *string {
	if p == nil {
		return nil
	}
	return p.DeviceName
}

func (p *PlayerSetStateGlobals) GetMarketplace() *string {
	if p == nil {
		return nil
	}
	return p.Marketplace
}

// QueryParamState - The desired playback state
type QueryParamState string

const (
	QueryParamStatePlaying QueryParamState = "playing"
	QueryParamStatePaused  QueryParamState = "paused"
	QueryParamStateStopped QueryParamState = "stopped"
)

func (e QueryParamState) ToPointer() *QueryParamState {
	return &e
}
func (e *QueryParamState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "playing":
		fallthrough
	case "paused":
		fallthrough
	case "stopped":
		*e = QueryParamState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamState: %v", v)
	}
}

type PlayerSetStateRequest struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
	// The client identifier of the target device to control. If omitted, the command is sent to the default/active client.
	XPlexTargetClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Target-Client-Identifier"`
	// The desired playback state
	State *QueryParamState `queryParam:"style=form,explode=true,name=state"`
}

func (p PlayerSetStateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlayerSetStateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlayerSetStateRequest) GetAccepts() *components.Accepts {
	if p == nil {
		return nil
	}
	return p.Accepts
}

func (p *PlayerSetStateRequest) GetClientIdentifier() *string {
	if p == nil {
		return nil
	}
	return p.ClientIdentifier
}

func (p *PlayerSetStateRequest) GetProduct() *string {
	if p == nil {
		return nil
	}
	return p.Product
}

func (p *PlayerSetStateRequest) GetVersion() *string {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *PlayerSetStateRequest) GetPlatform() *string {
	if p == nil {
		return nil
	}
	return p.Platform
}

func (p *PlayerSetStateRequest) GetPlatformVersion() *string {
	if p == nil {
		return nil
	}
	return p.PlatformVersion
}

func (p *PlayerSetStateRequest) GetDevice() *string {
	if p == nil {
		return nil
	}
	return p.Device
}

func (p *PlayerSetStateRequest) GetModel() *string {
	if p == nil {
		return nil
	}
	return p.Model
}

func (p *PlayerSetStateRequest) GetDeviceVendor() *string {
	if p == nil {
		return nil
	}
	return p.DeviceVendor
}

func (p *PlayerSetStateRequest) GetDeviceName() *string {
	if p == nil {
		return nil
	}
	return p.DeviceName
}

func (p *PlayerSetStateRequest) GetMarketplace() *string {
	if p == nil {
		return nil
	}
	return p.Marketplace
}

func (p *PlayerSetStateRequest) GetXPlexTargetClientIdentifier() *string {
	if p == nil {
		return nil
	}
	return p.XPlexTargetClientIdentifier
}

func (p *PlayerSetStateRequest) GetState() *QueryParamState {
	if p == nil {
		return nil
	}
	return p.State
}

type PlayerSetStateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	SuccessResponse *components.SuccessResponse
}

func (p *PlayerSetStateResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PlayerSetStateResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PlayerSetStateResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PlayerSetStateResponse) GetSuccessResponse() *components.SuccessResponse {
	if p == nil {
		return nil
	}
	return p.SuccessResponse
}
