// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type BadRequestErrors struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int    `json:"status,omitempty"`
}

func (b *BadRequestErrors) GetCode() *int {
	if b == nil {
		return nil
	}
	return b.Code
}

func (b *BadRequestErrors) GetMessage() *string {
	if b == nil {
		return nil
	}
	return b.Message
}

func (b *BadRequestErrors) GetStatus() *int {
	if b == nil {
		return nil
	}
	return b.Status
}

type BadRequest struct {
	Errors []BadRequestErrors `json:"errors,omitempty"`
}

var _ error = &BadRequest{}

func (e *BadRequest) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
