// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type Errors struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int    `json:"status,omitempty"`
}

func (e *Errors) GetCode() *int {
	if e == nil {
		return nil
	}
	return e.Code
}

func (e *Errors) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}

func (e *Errors) GetStatus() *int {
	if e == nil {
		return nil
	}
	return e.Status
}

// Error - Unauthorized
type Error struct {
	Errors []Errors `json:"errors,omitempty"`
}

var _ error = &Error{}

func (e *Error) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
