// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AddedQueueItem struct {
	// The queue item id that was added or the existing one if an item already exists in this queue with the same parameters
	ID *int64 `json:"id,omitempty"`
	// The key added to the queue
	Key *string `json:"key,omitempty"`
}

func (a *AddedQueueItem) GetID() *int64 {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AddedQueueItem) GetKey() *string {
	if a == nil {
		return nil
	}
	return a.Key
}
