// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/LukeHagar/plexgo/internal/utils"
)

type AllowSync3 string

const (
	AllowSync3Zero AllowSync3 = "0"
	AllowSync3One  AllowSync3 = "1"
)

func (e AllowSync3) ToPointer() *AllowSync3 {
	return &e
}
func (e *AllowSync3) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "0":
		fallthrough
	case "1":
		*e = AllowSync3(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AllowSync3: %v", v)
	}
}

type AllowSyncType string

const (
	AllowSyncTypeBoolean    AllowSyncType = "boolean"
	AllowSyncTypeAllowSync3 AllowSyncType = "AllowSync_3"
)

type AllowSync struct {
	Boolean    *bool       `queryParam:"inline" union:"member"`
	AllowSync3 *AllowSync3 `queryParam:"inline" union:"member"`

	Type AllowSyncType
}

func CreateAllowSyncBoolean(boolean bool) AllowSync {
	typ := AllowSyncTypeBoolean

	return AllowSync{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateAllowSyncAllowSync3(allowSync3 AllowSync3) AllowSync {
	typ := AllowSyncTypeAllowSync3

	return AllowSync{
		AllowSync3: &allowSync3,
		Type:       typ,
	}
}

func (u *AllowSync) UnmarshalJSON(data []byte) error {

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = AllowSyncTypeBoolean
		return nil
	}

	var allowSync3 AllowSync3 = AllowSync3("")
	if err := utils.UnmarshalJSON(data, &allowSync3, "", true, nil); err == nil {
		u.AllowSync3 = &allowSync3
		u.Type = AllowSyncTypeAllowSync3
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AllowSync", string(data))
}

func (u AllowSync) MarshalJSON() ([]byte, error) {
	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.AllowSync3 != nil {
		return utils.MarshalJSON(u.AllowSync3, "", true)
	}

	return nil, errors.New("could not marshal union type AllowSync: all fields are null")
}
