// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthTokenResponse struct {
	// The Plex authentication token
	AuthToken        *string `json:"authToken,omitempty"`
	ClientIdentifier *string `json:"clientIdentifier,omitempty"`
	// JWT token for device authentication
	Jwt *string `json:"jwt,omitempty"`
}

func (a *AuthTokenResponse) GetAuthToken() *string {
	if a == nil {
		return nil
	}
	return a.AuthToken
}

func (a *AuthTokenResponse) GetClientIdentifier() *string {
	if a == nil {
		return nil
	}
	return a.ClientIdentifier
}

func (a *AuthTokenResponse) GetJwt() *string {
	if a == nil {
		return nil
	}
	return a.Jwt
}
