// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Keys struct {
	Alg *string `json:"alg,omitempty"`
	E   *string `json:"e,omitempty"`
	Kid *string `json:"kid,omitempty"`
	Kty *string `json:"kty,omitempty"`
	N   *string `json:"n,omitempty"`
	Use *string `json:"use,omitempty"`
}

func (k *Keys) GetAlg() *string {
	if k == nil {
		return nil
	}
	return k.Alg
}

func (k *Keys) GetE() *string {
	if k == nil {
		return nil
	}
	return k.E
}

func (k *Keys) GetKid() *string {
	if k == nil {
		return nil
	}
	return k.Kid
}

func (k *Keys) GetKty() *string {
	if k == nil {
		return nil
	}
	return k.Kty
}

func (k *Keys) GetN() *string {
	if k == nil {
		return nil
	}
	return k.N
}

func (k *Keys) GetUse() *string {
	if k == nil {
		return nil
	}
	return k.Use
}

type AuthKeysResponse struct {
	Keys []Keys `json:"keys,omitempty"`
}

func (a *AuthKeysResponse) GetKeys() []Keys {
	if a == nil {
		return nil
	}
	return a.Keys
}
