// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ChannelResponseMediaContainer - `MediaContainer` is the root element of most Plex API responses. It serves as a generic container for various types of content (Metadata, Hubs, Directories, etc.) and includes pagination information (offset, size, totalSize) when applicable.
// Common attributes: - identifier: Unique identifier for this container - size: Number of items in this response page - totalSize: Total number of items available (for pagination) - offset: Starting index of this page (for pagination)
// The container often "hoists" common attributes from its children. For example, if all tracks in a container share the same album title, the `parentTitle` attribute may appear on the MediaContainer rather than being repeated on each track.
type ChannelResponseMediaContainer struct {
	Identifier *string `json:"identifier,omitempty"`
	// The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
	Offset *int64 `json:"offset,omitempty"`
	Size   *int64 `json:"size,omitempty"`
	// The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
	TotalSize *int64    `json:"totalSize,omitempty"`
	Channel   []Channel `json:"Channel,omitempty"`
}

func (c *ChannelResponseMediaContainer) GetIdentifier() *string {
	if c == nil {
		return nil
	}
	return c.Identifier
}

func (c *ChannelResponseMediaContainer) GetOffset() *int64 {
	if c == nil {
		return nil
	}
	return c.Offset
}

func (c *ChannelResponseMediaContainer) GetSize() *int64 {
	if c == nil {
		return nil
	}
	return c.Size
}

func (c *ChannelResponseMediaContainer) GetTotalSize() *int64 {
	if c == nil {
		return nil
	}
	return c.TotalSize
}

func (c *ChannelResponseMediaContainer) GetChannel() []Channel {
	if c == nil {
		return nil
	}
	return c.Channel
}

type ChannelResponse struct {
	MediaContainer *ChannelResponseMediaContainer `json:"MediaContainer,omitempty"`
}

func (c *ChannelResponse) GetMediaContainer() *ChannelResponseMediaContainer {
	if c == nil {
		return nil
	}
	return c.MediaContainer
}
