// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ClaimTokenResponse struct {
	// The claim token for server authentication
	Token *string `json:"token,omitempty"`
}

func (c *ClaimTokenResponse) GetToken() *string {
	if c == nil {
		return nil
	}
	return c.Token
}
