// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ConnectionInfo struct {
	AccessToken      *string      `json:"accessToken,omitempty"`
	ClientIdentifier *string      `json:"clientIdentifier,omitempty"`
	Connection       []Connection `json:"Connection,omitempty"`
	Name             *string      `json:"name,omitempty"`
}

func (c *ConnectionInfo) GetAccessToken() *string {
	if c == nil {
		return nil
	}
	return c.AccessToken
}

func (c *ConnectionInfo) GetClientIdentifier() *string {
	if c == nil {
		return nil
	}
	return c.ClientIdentifier
}

func (c *ConnectionInfo) GetConnection() []Connection {
	if c == nil {
		return nil
	}
	return c.Connection
}

func (c *ConnectionInfo) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}
