// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Status - The state of this queue
//   - deciding: At least one item is still being decided
//   - waiting: At least one item is waiting for transcode and none are currently transcoding
//   - processing: At least one item is being transcoded
//   - done: All items are available (or potentially expired)
//   - error: At least one item has encountered an error
type Status string

const (
	StatusDeciding   Status = "deciding"
	StatusWaiting    Status = "waiting"
	StatusProcessing Status = "processing"
	StatusDone       Status = "done"
	StatusError      Status = "error"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "deciding":
		fallthrough
	case "waiting":
		fallthrough
	case "processing":
		fallthrough
	case "done":
		fallthrough
	case "error":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

type DownloadQueue struct {
	ID        *int64 `json:"id,omitempty"`
	ItemCount *int64 `json:"itemCount,omitempty"`
	// The state of this queue
	//   - deciding: At least one item is still being decided
	//   - waiting: At least one item is waiting for transcode and none are currently transcoding
	//   - processing: At least one item is being transcoded
	//   - done: All items are available (or potentially expired)
	//   - error: At least one item has encountered an error
	Status *Status `json:"status,omitempty"`
}

func (d *DownloadQueue) GetID() *int64 {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DownloadQueue) GetItemCount() *int64 {
	if d == nil {
		return nil
	}
	return d.ItemCount
}

func (d *DownloadQueue) GetStatus() *Status {
	if d == nil {
		return nil
	}
	return d.Status
}
