// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Flavor - - `0`: The country is divided into regions, and following the key will lead to a list of regions.
// - `1`: The county is divided by postal codes, and an example code is returned in `example`.
// - `2`: The country has a single postal code, returned in `example`.
type Flavor int64

const (
	FlavorZero Flavor = 0
	FlavorOne  Flavor = 1
	FlavorTwo  Flavor = 2
)

func (e Flavor) ToPointer() *Flavor {
	return &e
}
func (e *Flavor) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 0:
		fallthrough
	case 1:
		fallthrough
	case 2:
		*e = Flavor(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Flavor: %v", v)
	}
}

type EPGCountry struct {
	Title   *string `json:"title,omitempty"`
	Type    *string `json:"type,omitempty"`
	Example *string `json:"example,omitempty"`
	// Three letter code
	Code *string `json:"code,omitempty"`
	// - `0`: The country is divided into regions, and following the key will lead to a list of regions.
	// - `1`: The county is divided by postal codes, and an example code is returned in `example`.
	// - `2`: The country has a single postal code, returned in `example`.
	Flavor *Flavor `json:"flavor,omitempty"`
	Key    *string `json:"key,omitempty"`
	// Three letter language code
	Language *string `json:"language,omitempty"`
	// The title of the language
	LanguageTitle *string `json:"languageTitle,omitempty"`
}

func (e *EPGCountry) GetTitle() *string {
	if e == nil {
		return nil
	}
	return e.Title
}

func (e *EPGCountry) GetType() *string {
	if e == nil {
		return nil
	}
	return e.Type
}

func (e *EPGCountry) GetExample() *string {
	if e == nil {
		return nil
	}
	return e.Example
}

func (e *EPGCountry) GetCode() *string {
	if e == nil {
		return nil
	}
	return e.Code
}

func (e *EPGCountry) GetFlavor() *Flavor {
	if e == nil {
		return nil
	}
	return e.Flavor
}

func (e *EPGCountry) GetKey() *string {
	if e == nil {
		return nil
	}
	return e.Key
}

func (e *EPGCountry) GetLanguage() *string {
	if e == nil {
		return nil
	}
	return e.Language
}

func (e *EPGCountry) GetLanguageTitle() *string {
	if e == nil {
		return nil
	}
	return e.LanguageTitle
}
