// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetResponses200MediaContainer - `MediaContainer` is the root element of most Plex API responses. It serves as a generic container for various types of content (Metadata, Hubs, Directories, etc.) and includes pagination information (offset, size, totalSize) when applicable.
// Common attributes: - identifier: Unique identifier for this container - size: Number of items in this response page - totalSize: Total number of items available (for pagination) - offset: Starting index of this page (for pagination)
// The container often "hoists" common attributes from its children. For example, if all tracks in a container share the same album title, the `parentTitle` attribute may appear on the MediaContainer rather than being repeated on each track.
type GetResponses200MediaContainer struct {
	Identifier *string `json:"identifier,omitempty"`
	// The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
	Offset *int64 `json:"offset,omitempty"`
	Size   *int64 `json:"size,omitempty"`
	// The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
	TotalSize *int64       `json:"totalSize,omitempty"`
	Hub       []ManagedHub `json:"Hub,omitempty"`
}

func (g *GetResponses200MediaContainer) GetIdentifier() *string {
	if g == nil {
		return nil
	}
	return g.Identifier
}

func (g *GetResponses200MediaContainer) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetResponses200MediaContainer) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

func (g *GetResponses200MediaContainer) GetTotalSize() *int64 {
	if g == nil {
		return nil
	}
	return g.TotalSize
}

func (g *GetResponses200MediaContainer) GetHub() []ManagedHub {
	if g == nil {
		return nil
	}
	return g.Hub
}

// #region class-body-getresponses200mediacontainer
// #endregion class-body-getresponses200mediacontainer

// GetResponses200 - OK
type GetResponses200 struct {
	MediaContainer *GetResponses200MediaContainer `json:"MediaContainer,omitempty"`
}

func (g *GetResponses200) GetMediaContainer() *GetResponses200MediaContainer {
	if g == nil {
		return nil
	}
	return g.MediaContainer
}

// #region class-body-getresponses200
// #endregion class-body-getresponses200
