// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/LukeHagar/plexgo/internal/utils"
)

// Jwk - JSON Web Key for device authentication
type Jwk struct {
	Crv *string `json:"crv,omitempty"`
	Kid *string `json:"kid,omitempty"`
	Kty *string `json:"kty,omitempty"`
	X   *string `json:"x,omitempty"`
}

func (j *Jwk) GetCrv() *string {
	if j == nil {
		return nil
	}
	return j.Crv
}

func (j *Jwk) GetKid() *string {
	if j == nil {
		return nil
	}
	return j.Kid
}

func (j *Jwk) GetKty() *string {
	if j == nil {
		return nil
	}
	return j.Kty
}

func (j *Jwk) GetX() *string {
	if j == nil {
		return nil
	}
	return j.X
}

type JWKRegistrationRequest struct {
	// JSON Web Key for device authentication
	Jwk *Jwk `json:"jwk,omitempty"`
	// Request strong authentication
	Strong *bool `default:"false" json:"strong"`
}

func (j JWKRegistrationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JWKRegistrationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (j *JWKRegistrationRequest) GetJwk() *Jwk {
	if j == nil {
		return nil
	}
	return j.Jwk
}

func (j *JWKRegistrationRequest) GetStrong() *bool {
	if j == nil {
		return nil
	}
	return j.Strong
}
