// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MediaContainerWithPlayQueue - A media container representing a play queue.
type MediaContainerWithPlayQueue struct {
	Identifier *string `json:"identifier,omitempty"`
	// The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
	Offset *int64 `json:"offset,omitempty"`
	Size   *int64 `json:"size,omitempty"`
	// The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
	TotalSize                       *int64  `json:"totalSize,omitempty"`
	PlayQueueID                     *int64  `json:"playQueueID,omitempty"`
	PlayQueueLastAddedItemID        *int64  `json:"playQueueLastAddedItemID,omitempty"`
	PlayQueueSelectedItemID         *int64  `json:"playQueueSelectedItemID,omitempty"`
	PlayQueueSelectedItemOffset     *int64  `json:"playQueueSelectedItemOffset,omitempty"`
	PlayQueueSelectedMetadataItemID *int64  `json:"playQueueSelectedMetadataItemID,omitempty"`
	PlayQueueShuffled               *bool   `json:"playQueueShuffled,omitempty"`
	PlayQueueSourceURI              *string `json:"playQueueSourceURI,omitempty"`
	PlayQueueTotalCount             *int64  `json:"playQueueTotalCount,omitempty"`
	PlayQueueVersion                *int64  `json:"playQueueVersion,omitempty"`
}

func (m *MediaContainerWithPlayQueue) GetIdentifier() *string {
	if m == nil {
		return nil
	}
	return m.Identifier
}

func (m *MediaContainerWithPlayQueue) GetOffset() *int64 {
	if m == nil {
		return nil
	}
	return m.Offset
}

func (m *MediaContainerWithPlayQueue) GetSize() *int64 {
	if m == nil {
		return nil
	}
	return m.Size
}

func (m *MediaContainerWithPlayQueue) GetTotalSize() *int64 {
	if m == nil {
		return nil
	}
	return m.TotalSize
}

func (m *MediaContainerWithPlayQueue) GetPlayQueueID() *int64 {
	if m == nil {
		return nil
	}
	return m.PlayQueueID
}

func (m *MediaContainerWithPlayQueue) GetPlayQueueLastAddedItemID() *int64 {
	if m == nil {
		return nil
	}
	return m.PlayQueueLastAddedItemID
}

func (m *MediaContainerWithPlayQueue) GetPlayQueueSelectedItemID() *int64 {
	if m == nil {
		return nil
	}
	return m.PlayQueueSelectedItemID
}

func (m *MediaContainerWithPlayQueue) GetPlayQueueSelectedItemOffset() *int64 {
	if m == nil {
		return nil
	}
	return m.PlayQueueSelectedItemOffset
}

func (m *MediaContainerWithPlayQueue) GetPlayQueueSelectedMetadataItemID() *int64 {
	if m == nil {
		return nil
	}
	return m.PlayQueueSelectedMetadataItemID
}

func (m *MediaContainerWithPlayQueue) GetPlayQueueShuffled() *bool {
	if m == nil {
		return nil
	}
	return m.PlayQueueShuffled
}

func (m *MediaContainerWithPlayQueue) GetPlayQueueSourceURI() *string {
	if m == nil {
		return nil
	}
	return m.PlayQueueSourceURI
}

func (m *MediaContainerWithPlayQueue) GetPlayQueueTotalCount() *int64 {
	if m == nil {
		return nil
	}
	return m.PlayQueueTotalCount
}

func (m *MediaContainerWithPlayQueue) GetPlayQueueVersion() *int64 {
	if m == nil {
		return nil
	}
	return m.PlayQueueVersion
}
