// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NotificationContainer struct {
	// The notification type
	Type                         *string
	PlaySessionStateNotification []PlaySessionStateNotification
	ReachabilityNotification     []ReachabilityNotification
	// Number of notifications
	Size               *int64
	StatusNotification []StatusNotification
	TimelineEntry      []TimelineEntry
}

func (n *NotificationContainer) GetType() *string {
	if n == nil {
		return nil
	}
	return n.Type
}

func (n *NotificationContainer) GetPlaySessionStateNotification() []PlaySessionStateNotification {
	if n == nil {
		return nil
	}
	return n.PlaySessionStateNotification
}

func (n *NotificationContainer) GetReachabilityNotification() []ReachabilityNotification {
	if n == nil {
		return nil
	}
	return n.ReachabilityNotification
}

func (n *NotificationContainer) GetSize() *int64 {
	if n == nil {
		return nil
	}
	return n.Size
}

func (n *NotificationContainer) GetStatusNotification() []StatusNotification {
	if n == nil {
		return nil
	}
	return n.StatusNotification
}

func (n *NotificationContainer) GetTimelineEntry() []TimelineEntry {
	if n == nil {
		return nil
	}
	return n.TimelineEntry
}
