// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type State string

const (
	StatePlaying State = "playing"
	StatePaused  State = "paused"
	StateStopped State = "stopped"
)

func (e State) ToPointer() *State {
	return &e
}
func (e *State) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "playing":
		fallthrough
	case "paused":
		fallthrough
	case "stopped":
		*e = State(v)
		return nil
	default:
		return fmt.Errorf("invalid value for State: %v", v)
	}
}

// PlaySessionStateNotification - Real-time playback state change notification
type PlaySessionStateNotification struct {
	Controllable     *string
	GUID             *string
	Key              *string
	PlayQueueID      *int64
	PlayQueueItemID  *int64
	RatingKey        *string
	SessionKey       *string
	State            *State
	TranscodeSession *string
	URL              *string
	ViewOffset       *int64
}

func (p *PlaySessionStateNotification) GetControllable() *string {
	if p == nil {
		return nil
	}
	return p.Controllable
}

func (p *PlaySessionStateNotification) GetGUID() *string {
	if p == nil {
		return nil
	}
	return p.GUID
}

func (p *PlaySessionStateNotification) GetKey() *string {
	if p == nil {
		return nil
	}
	return p.Key
}

func (p *PlaySessionStateNotification) GetPlayQueueID() *int64 {
	if p == nil {
		return nil
	}
	return p.PlayQueueID
}

func (p *PlaySessionStateNotification) GetPlayQueueItemID() *int64 {
	if p == nil {
		return nil
	}
	return p.PlayQueueItemID
}

func (p *PlaySessionStateNotification) GetRatingKey() *string {
	if p == nil {
		return nil
	}
	return p.RatingKey
}

func (p *PlaySessionStateNotification) GetSessionKey() *string {
	if p == nil {
		return nil
	}
	return p.SessionKey
}

func (p *PlaySessionStateNotification) GetState() *State {
	if p == nil {
		return nil
	}
	return p.State
}

func (p *PlaySessionStateNotification) GetTranscodeSession() *string {
	if p == nil {
		return nil
	}
	return p.TranscodeSession
}

func (p *PlaySessionStateNotification) GetURL() *string {
	if p == nil {
		return nil
	}
	return p.URL
}

func (p *PlaySessionStateNotification) GetViewOffset() *int64 {
	if p == nil {
		return nil
	}
	return p.ViewOffset
}
