// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/LukeHagar/plexgo/internal/utils"
	"time"
)

// PlexDeviceProtocol - The protocol used for the connection (http, https, etc)
type PlexDeviceProtocol string

const (
	PlexDeviceProtocolHTTP  PlexDeviceProtocol = "http"
	PlexDeviceProtocolHTTPS PlexDeviceProtocol = "https"
)

func (e PlexDeviceProtocol) ToPointer() *PlexDeviceProtocol {
	return &e
}
func (e *PlexDeviceProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "http":
		fallthrough
	case "https":
		*e = PlexDeviceProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlexDeviceProtocol: %v", v)
	}
}

type Connections struct {
	// The (ip) address or domain name used for the connection
	Address string `json:"address"`
	// If the connection is using IPv6
	IPv6 bool `json:"IPv6"`
	// If the connection is local address
	Local bool `json:"local"`
	// The port used for the connection
	Port int `json:"port"`
	// The protocol used for the connection (http, https, etc)
	Protocol PlexDeviceProtocol `json:"protocol"`
	// If the connection is relayed through plex.direct
	Relay bool `json:"relay"`
	// The full URI of the connection
	URI string `json:"uri"`
}

func (c *Connections) GetAddress() string {
	if c == nil {
		return ""
	}
	return c.Address
}

func (c *Connections) GetIPv6() bool {
	if c == nil {
		return false
	}
	return c.IPv6
}

func (c *Connections) GetLocal() bool {
	if c == nil {
		return false
	}
	return c.Local
}

func (c *Connections) GetPort() int {
	if c == nil {
		return 0
	}
	return c.Port
}

func (c *Connections) GetProtocol() PlexDeviceProtocol {
	if c == nil {
		return PlexDeviceProtocol("")
	}
	return c.Protocol
}

func (c *Connections) GetRelay() bool {
	if c == nil {
		return false
	}
	return c.Relay
}

func (c *Connections) GetURI() string {
	if c == nil {
		return ""
	}
	return c.URI
}

type PlexDevice struct {
	AccessToken            string        `json:"accessToken"`
	ClientIdentifier       string        `json:"clientIdentifier"`
	Connections            []Connections `json:"connections"`
	CreatedAt              time.Time     `json:"createdAt"`
	Device                 *string       `json:"device,omitempty"`
	DNSRebindingProtection bool          `json:"dnsRebindingProtection"`
	Home                   bool          `json:"home"`
	HTTPSRequired          bool          `json:"httpsRequired"`
	LastSeenAt             time.Time     `json:"lastSeenAt"`
	Name                   string        `json:"name"`
	NatLoopbackSupported   bool          `json:"natLoopbackSupported"`
	Owned                  bool          `json:"owned"`
	// ownerId is null when the device is owned by the token used to send the request
	OwnerID              *int64  `json:"ownerId"`
	Platform             *string `json:"platform,omitempty"`
	PlatformVersion      *string `json:"platformVersion,omitempty"`
	Presence             bool    `json:"presence"`
	Product              string  `json:"product"`
	ProductVersion       string  `json:"productVersion"`
	Provides             string  `json:"provides"`
	PublicAddress        string  `json:"publicAddress"`
	PublicAddressMatches bool    `json:"publicAddressMatches"`
	Relay                bool    `json:"relay"`
	SourceTitle          *string `json:"sourceTitle"`
	Synced               bool    `json:"synced"`
}

func (p PlexDevice) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlexDevice) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlexDevice) GetAccessToken() string {
	if p == nil {
		return ""
	}
	return p.AccessToken
}

func (p *PlexDevice) GetClientIdentifier() string {
	if p == nil {
		return ""
	}
	return p.ClientIdentifier
}

func (p *PlexDevice) GetConnections() []Connections {
	if p == nil {
		return []Connections{}
	}
	return p.Connections
}

func (p *PlexDevice) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PlexDevice) GetDevice() *string {
	if p == nil {
		return nil
	}
	return p.Device
}

func (p *PlexDevice) GetDNSRebindingProtection() bool {
	if p == nil {
		return false
	}
	return p.DNSRebindingProtection
}

func (p *PlexDevice) GetHome() bool {
	if p == nil {
		return false
	}
	return p.Home
}

func (p *PlexDevice) GetHTTPSRequired() bool {
	if p == nil {
		return false
	}
	return p.HTTPSRequired
}

func (p *PlexDevice) GetLastSeenAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.LastSeenAt
}

func (p *PlexDevice) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PlexDevice) GetNatLoopbackSupported() bool {
	if p == nil {
		return false
	}
	return p.NatLoopbackSupported
}

func (p *PlexDevice) GetOwned() bool {
	if p == nil {
		return false
	}
	return p.Owned
}

func (p *PlexDevice) GetOwnerID() *int64 {
	if p == nil {
		return nil
	}
	return p.OwnerID
}

func (p *PlexDevice) GetPlatform() *string {
	if p == nil {
		return nil
	}
	return p.Platform
}

func (p *PlexDevice) GetPlatformVersion() *string {
	if p == nil {
		return nil
	}
	return p.PlatformVersion
}

func (p *PlexDevice) GetPresence() bool {
	if p == nil {
		return false
	}
	return p.Presence
}

func (p *PlexDevice) GetProduct() string {
	if p == nil {
		return ""
	}
	return p.Product
}

func (p *PlexDevice) GetProductVersion() string {
	if p == nil {
		return ""
	}
	return p.ProductVersion
}

func (p *PlexDevice) GetProvides() string {
	if p == nil {
		return ""
	}
	return p.Provides
}

func (p *PlexDevice) GetPublicAddress() string {
	if p == nil {
		return ""
	}
	return p.PublicAddress
}

func (p *PlexDevice) GetPublicAddressMatches() bool {
	if p == nil {
		return false
	}
	return p.PublicAddressMatches
}

func (p *PlexDevice) GetRelay() bool {
	if p == nil {
		return false
	}
	return p.Relay
}

func (p *PlexDevice) GetSourceTitle() *string {
	if p == nil {
		return nil
	}
	return p.SourceTitle
}

func (p *PlexDevice) GetSynced() bool {
	if p == nil {
		return false
	}
	return p.Synced
}
