// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ReachabilityNotification - Server reachability status change notification
type ReachabilityNotification struct {
	Status *string
}

func (r *ReachabilityNotification) GetStatus() *string {
	if r == nil {
		return nil
	}
	return r.Status
}
