// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ReleaseState - The status of this update.
//
// - available - This release is available
// - downloading - This release is downloading
// - downloaded - This release has been downloaded
// - installing - This release is installing
// - tonight - This release will be installed tonight
// - skipped - This release has been skipped
// - error - This release has an error
// - notify - This release is only notifying it is available (typically because it cannot be installed on this setup)
// - done - This release is complete
type ReleaseState string

const (
	ReleaseStateAvailable   ReleaseState = "available"
	ReleaseStateDownloading ReleaseState = "downloading"
	ReleaseStateDownloaded  ReleaseState = "downloaded"
	ReleaseStateInstalling  ReleaseState = "installing"
	ReleaseStateTonight     ReleaseState = "tonight"
	ReleaseStateSkipped     ReleaseState = "skipped"
	ReleaseStateError       ReleaseState = "error"
	ReleaseStateNotify      ReleaseState = "notify"
	ReleaseStateDone        ReleaseState = "done"
)

func (e ReleaseState) ToPointer() *ReleaseState {
	return &e
}
func (e *ReleaseState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "available":
		fallthrough
	case "downloading":
		fallthrough
	case "downloaded":
		fallthrough
	case "installing":
		fallthrough
	case "tonight":
		fallthrough
	case "skipped":
		fallthrough
	case "error":
		fallthrough
	case "notify":
		fallthrough
	case "done":
		*e = ReleaseState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReleaseState: %v", v)
	}
}

type Release struct {
	// A list of what has been added in this version
	Added *string `json:"added,omitempty"`
	// The URL of where this update is available
	DownloadURL *string `json:"downloadURL,omitempty"`
	// A list of what has been fixed in this version
	Fixed *string `json:"fixed,omitempty"`
	// The URL key of the update
	Key *string `json:"key,omitempty"`
	// The status of this update.
	//
	// - available - This release is available
	// - downloading - This release is downloading
	// - downloaded - This release has been downloaded
	// - installing - This release is installing
	// - tonight - This release will be installed tonight
	// - skipped - This release has been skipped
	// - error - This release has an error
	// - notify - This release is only notifying it is available (typically because it cannot be installed on this setup)
	// - done - This release is complete
	State *ReleaseState `json:"state,omitempty"`
	// The version available
	Version *string `json:"version,omitempty"`
}

func (r *Release) GetAdded() *string {
	if r == nil {
		return nil
	}
	return r.Added
}

func (r *Release) GetDownloadURL() *string {
	if r == nil {
		return nil
	}
	return r.DownloadURL
}

func (r *Release) GetFixed() *string {
	if r == nil {
		return nil
	}
	return r.Fixed
}

func (r *Release) GetKey() *string {
	if r == nil {
		return nil
	}
	return r.Key
}

func (r *Release) GetState() *ReleaseState {
	if r == nil {
		return nil
	}
	return r.State
}

func (r *Release) GetVersion() *string {
	if r == nil {
		return nil
	}
	return r.Version
}
