// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SuccessResponse - A simple success indicator for operations that return no meaningful data
type SuccessResponse struct {
	Success *bool `json:"success,omitempty"`
}

func (s *SuccessResponse) GetSuccess() *bool {
	if s == nil {
		return nil
	}
	return s.Success
}
