// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TokenExchangeRequest struct {
	// Unique client identifier
	ClientIdentifier *string `json:"clientIdentifier,omitempty"`
	// JWT token to exchange for a Plex auth token
	Jwt *string `json:"jwt,omitempty"`
	// Requested scope for the token
	Scope *string `json:"scope,omitempty"`
}

func (t *TokenExchangeRequest) GetClientIdentifier() *string {
	if t == nil {
		return nil
	}
	return t.ClientIdentifier
}

func (t *TokenExchangeRequest) GetJwt() *string {
	if t == nil {
		return nil
	}
	return t.Jwt
}

func (t *TokenExchangeRequest) GetScope() *string {
	if t == nil {
		return nil
	}
	return t.Scope
}
