// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UltraBlurColors struct {
	// The color (hex) for the bottom left quadrant.
	BottomLeft *string `json:"bottomLeft,omitempty"`
	// The color (hex) for the bottom right quadrant.
	BottomRight *string `json:"bottomRight,omitempty"`
	// The color (hex) for the top left quadrant.
	TopLeft *string `json:"topLeft,omitempty"`
	// The color (hex) for the top right quadrant.
	TopRight *string `json:"topRight,omitempty"`
}

func (u *UltraBlurColors) GetBottomLeft() *string {
	if u == nil {
		return nil
	}
	return u.BottomLeft
}

func (u *UltraBlurColors) GetBottomRight() *string {
	if u == nil {
		return nil
	}
	return u.BottomRight
}

func (u *UltraBlurColors) GetTopLeft() *string {
	if u == nil {
		return nil
	}
	return u.TopLeft
}

func (u *UltraBlurColors) GetTopRight() *string {
	if u == nil {
		return nil
	}
	return u.TopRight
}
